### ISSUE TITLE
Enums in arguments are serialized in quotes 

### ISSUE THREAD

**Issue by VojtaStanek** [babyfish-ct/graphql-ts-client#15]
When there is an enum in query inlined arguments it is serialized as a string in quotes. See the following example - the `alignment` input field is an enum field. 

Current request:

```
mutation {
        someMutation(
                update: {alignment: "left"}
        ) {
                ok
                errorMessage
        }
}
```

Expected request:

```
mutation {
        someMutation(
                update: {alignment: left}
        ) {
                ok
                errorMessage
        }
}
```

I can work around it by sending the arguments in variables, but that's not ideal for my use case.

**Comment by VojtaStanek** [comment]
it's ok

**Comment by babyfish-ct** [comment]
Hi VojtaStanek

The issue is fixed, please upgrade to v3.1.2. 

After the validation for your scenes, if no problems, please close this issue .

-------------------------

BTW, a month ago, I told you this low priority work is delayed because I was working on another open source project. Now it is finished. It may be useful for you if you, your colleagues or your friends have Java developers: https://babyfish-ct.github.io/jimmer-doc/

**Comment by VojtaStanek** [comment]
I have updated to version 3.1.2 and I am getting the following error when running codegen?

```
/home/vojta/projects/mango/respekt-replicator/node_modules/graphql/type/index.js:254
  get: function get() {
                   ^

RangeError: Maximum call stack size exceeded
    at Object.get [as GraphQLScalarType] (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql/type/index.js:254:20)
    at Object.get [as GraphQLScalarType] (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql/index.js:45:19)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:55:39)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:78:22)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:62:25)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:59:25)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:78:22)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:62:25)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:59:25)
    at EnumInputMetadataWriter.collectEnumMetaTypes (/home/vojta/projects/mango/respekt-replicator/node_modules/graphql-ts-client-codegen/dist/EnumInputMetadataWriter.js:78:22)
```

Is this sufficient information to know what to fix? Thanks!

**Comment by babyfish-ct** [comment]
Give me your SDL

**Comment by babyfish-ct** [comment]
Because 3.1.3 or 3.1.4 fixed it.

Later, 3.1.5 will be released.
