### ISSUE TITLE
Error on codegen

### ISSUE THREAD

**Issue by emersonbottero** [babyfish-ct/graphql-ts-client#7]
While following [this tutorial](https://github.com/babyfish-ct/graphql-ts-client/blob/master/get-start-async.md) I received
``` bash
 The type "ChannelGroupConnection" is connection, its field "edges" must be not-null list
  at connectionTypeTuple (...\node_modules\.pnpm\graphql-ts-client-codegen@3.0.10\node_modules\graphql-ts-client-codegen\dist\Generator.js:341:31)
    at AsyncGenerator.<anonymous> (...\node_modules\.pnpm\graphql-ts-client-codegen@3.0.10\node_modules\graphql-ts-client-codegen\dist\Generator.js:55:39)
    at Generator.next (<anonymous>)
```

the only difference is
I changed 
``` js
return loadRemoteSchema("https://paas-api.pluralsight.com/graphql", { authorization: `Bearer ...´
```

and I removed the 
```js
 defaultFetcherExcludeMap: {
      "Department": ["avgSalary"]
    },
```

you can see all return "types" in the [API docs](https://developer.pluralsight.com/schema/channel/channelGroup)

P.S.: I can't change the API so I'm stuck...

**Comment by babyfish-ct** [comment]
Please give the sdl to me, I cannot access it

**Comment by babyfish-ct** [comment]
Now the "connection.edges" cannot be null, is it necessary to make it be nullable?
